### ISSUE TITLE
create comment model: approved_comments.count doesn't work

### ISSUE THREAD

**Issue by junhyungjin** [DjangoGirls/tutorial-extensions#71] opened 2017-02-07 15:33 UTC
To print post.approved_comments.count on post_list.html doesn't show anything.
post.comments.count shows the right number of comments but post.approved_comments.count doesn't
Anyone has the answer?

**Comment by ndik11** [comment] 2017-02-09 08:41
Have the same problem

**Comment by bbbruno04** [comment] 2017-02-25 15:30
I had the same issue when working through the "create comment model" tutorial. I was mistakenly putting the approved_comments function in the Comment class instead of the Post class in my models.py. Hope that helps!

**Comment by Pedro-Webdev** [comment] 2017-06-18 19:17
Thx Sola. I had the same issue and your tweak just did it. ; )

**Comment by Pedro-Webdev** [comment] 2017-06-18 19:25
I added same functionality for approved comments as posts at post_detail.html, where you can send to trash undesired ones, even after you approved them. That way it isn't necessary to open Admin to erase them. Starts at {% if user.is_authenticated and comment.approved_comment %}...

    {% for comment in post.comments.all %}
    	        {% if user.is_authenticated or comment.approved_comment %}
			<div>
				
				{{ comment.created_date|date:'d-m-Y' }}
				
				{% if not comment.approved_comment %}
					<a href="{% url 'comment_remove' pk=comment.pk %}">
					<i class="fa fa-times"></i>
					</a>
					<a href="{% url 'comment_approve' pk=comment.pk %}">
					<i class="fa fa-check"></i>
					</a>
				{% endif %}
                               
				{% if user.is_authenticated and comment.approved_comment %}
					<a href="{% url 'comment_remove' pk=comment.pk %}">
					<i class="fa fa-trash"></i>
					</a>
				{% endif %}
				
				<strong> {{ comment.author }} </strong>			
				<p>{{ comment.text|linebreaks }}</p>
			</div>
			{% endif %}

		{% empty %}
			<p>No comments here yet. : (</p>
    	{% endfor %}

**Comment by aniav** [comment] 2017-09-30 20:49
It seems this is not really an issue in the tutorial, so I am closing that now. Thank you! 🌮

**Closed by aniav** 2017-09-30 20:49 UTC

**Comment by Narsimhuluk** [comment] 2018-12-24 14:21
@SolaOmi , yes you are right, as per your comment the problem is rectified in my tutorial and corrected by placing approve_comment() in below of Post function in model.py
